export const QUESTION_BANK = [
  { question: "What is the capital of India?", answer: "New Delhi" },
  { question: "What is the largest planet in our solar system?", answer: "Jupiter" },
  { question: "Who painted the Mona Lisa?", answer: "Leonardo da Vinci" },
  { question: "What is the chemical symbol for gold?", answer: "Au" },
  { question: "What year did World War II end?", answer: "1945" },
  { question: "What is the smallest country in the world?", answer: "Vatican City" },
  { question: "Who wrote Romeo and Juliet?", answer: "William Shakespeare" },
  { question: "What is the speed of light?", answer: "299,792,458 m/s" },
  { question: "What is the capital of France?", answer: "Paris" },
  { question: "How many continents are there?", answer: "7" },
  { question: "What is the longest river in the world?", answer: "The Nile" },
  { question: "Who invented the telephone?", answer: "Alexander Graham Bell" },
  { question: "What is the hardest natural substance?", answer: "Diamond" },
  { question: "What is the currency of Japan?", answer: "Yen" },
  { question: "Who was the first person on the moon?", answer: "Neil Armstrong" },
  { question: "What is the largest ocean?", answer: "Pacific Ocean" },
  { question: "What is the boiling point of water?", answer: "100°C" },
  { question: "Who wrote Harry Potter?", answer: "J.K. Rowling" },
  { question: "What is the capital of Australia?", answer: "Canberra" },
  { question: "How many bones are in the human body?", answer: "206" },
  { question: "What is the capital of India?", answer: "New Delhi" },
{ question: "What is the capital of France?", answer: "Paris" },
{ question: "What is the capital of Japan?", answer: "Tokyo" },
{ question: "What is the largest planet in our solar system?", answer: "Jupiter" },
{ question: "What is the smallest planet in our solar system?", answer: "Mercury" },
{ question: "What planet is known as the Red Planet?", answer: "Mars" },
{ question: "Who painted the Mona Lisa?", answer: "Leonardo da Vinci" },
{ question: "Who painted The Starry Night?", answer: "Vincent van Gogh" },
{ question: "Who wrote Romeo and Juliet?", answer: "William Shakespeare" },
{ question: "Who wrote The Hobbit?", answer: "J. R. R. Tolkien" },
{ question: "Who discovered penicillin?", answer: "Alexander Fleming" },
{ question: "Who proposed the theory of relativity?", answer: "Albert Einstein" },
{ question: "What is the hardest natural substance on Earth?", answer: "Diamond" },
{ question: "What gas do plants breathe in?", answer: "Carbon dioxide" },
{ question: "What gas do humans breathe out?", answer: "Carbon dioxide" },
{ question: "What is the chemical symbol for water?", answer: "H2O" },
{ question: "What is the chemical symbol for gold?", answer: "Au" },
{ question: "What is the chemical symbol for oxygen?", answer: "O" },
{ question: "What is the tallest mountain in the world?", answer: "Mount Everest" },
{ question: "What is the longest river in the world?", answer: "Nile" },
{ question: "What is the largest ocean on Earth?", answer: "Pacific Ocean" },
{ question: "What is the largest desert on Earth?", answer: "Sahara Desert" },
{ question: "What is the fastest land animal?", answer: "Cheetah" },
{ question: "What is the largest mammal?", answer: "Blue whale" },
{ question: "What is the tallest animal?", answer: "Giraffe" },
{ question: "What is the currency of Japan?", answer: "Yen" },
{ question: "What is the currency of the United Kingdom?", answer: "Pound" },
{ question: "What is the currency of the United States?", answer: "Dollar" },
{ question: "How many continents are there?", answer: "Seven" },
{ question: "How many planets are in our solar system?", answer: "Eight" },
{ question: "How many bones are in the adult human body?", answer: "206" },
{ question: "How many players are on a football team on the field?", answer: "11" },
{ question: "How many stripes are on the US flag?", answer: "13" },
{ question: "How many days are in a leap year?", answer: "366" },
{ question: "What is the largest country by area?", answer: "Russia" },
{ question: "What is the smallest country in the world?", answer: "Vatican City" },
{ question: "What is the most spoken language in the world?", answer: "English" },
{ question: "What is the national bird of the United States?", answer: "Bald eagle" },
{ question: "What is the main gas in the Earth's atmosphere?", answer: "Nitrogen" },
{ question: "What organ pumps blood through the body?", answer: "Heart" },
{ question: "What organ controls the body?", answer: "Brain" },
{ question: "What part of the body has the smallest bones?", answer: "Ear" },
{ question: "What is the largest internal organ?", answer: "Liver" },
{ question: "In which country is the Taj Mahal located?", answer: "India" },
{ question: "In which country are the pyramids of Giza located?", answer: "Egypt" },
{ question: "In which country is the Great Wall located?", answer: "China" },
{ question: "What year did World War II end?", answer: "1945" },
{ question: "What year did the Titanic sink?", answer: "1912" },
{ question: "What year did humans first land on the Moon?", answer: "1969" },
{ question: "Who was the first man to walk on the Moon?", answer: "Neil Armstrong" },
{ question: "Who was the first Prime Minister of India?", answer: "Jawaharlal Nehru" },
{ question: "Who was the first President of the United States?", answer: "George Washington" },
{ question: "What is the longest bone in the human body?", answer: "Femur" },
{ question: "What is the smallest ocean on Earth?", answer: "Arctic Ocean" },
{ question: "What is the name of the galaxy we live in?", answer: "Milky Way" },
{ question: "What is the nearest star to Earth?", answer: "Sun" },
{ question: "What is the closest planet to the Sun?", answer: "Mercury" },
{ question: "What is the largest island in the world?", answer: "Greenland" },
{ question: "What is the capital of Australia?", answer: "Canberra" },
{ question: "What is the capital of Italy?", answer: "Rome" },
{ question: "What is the capital of Canada?", answer: "Ottawa" },
{ question: "What is the capital of Brazil?", answer: "Brasilia" },
{ question: "What metal is liquid at room temperature?", answer: "Mercury" },
{ question: "What is the heaviest naturally occurring element?", answer: "Uranium" },
{ question: "What is the main ingredient in bread?", answer: "Flour" },
{ question: "What is the main ingredient in guacamole?", answer: "Avocado" },
{ question: "What fruit is known as the king of fruits in India?", answer: "Mango" },
{ question: "What is the hottest planet in our solar system?", answer: "Venus" },
{ question: "Which planet has the most moons?", answer: "Saturn" },
{ question: "Which animal is known as the ship of the desert?", answer: "Camel" },
{ question: "Which bird can fly backward?", answer: "Hummingbird" },
{ question: "Which continent is known as the frozen continent?", answer: "Antarctica" },
{ question: "Which country invented paper?", answer: "China" },
{ question: "Which country invented pizza?", answer: "Italy" },
{ question: "Which country invented sushi?", answer: "Japan" },
{ question: "What is the most famous clock tower in London?", answer: "Big Ben" },
{ question: "What is the tallest building in the world?", answer: "Burj Khalifa" },
{ question: "What city is known as the city of love?", answer: "Paris" },
{ question: "What city is known as the big apple?", answer: "New York City" },
{ question: "What does FIFA stand for?", answer: "Federation Internationale de Football Association" },
{ question: "What does GPS stand for?", answer: "Global Positioning System" },
{ question: "What does ATM stand for?", answer: "Automated Teller Machine" },
{ question: "What is the longest word in the English dictionary?", answer: "Pneumonoultramicroscopicsilicovolcanoconiosis" },
{ question: "What sport uses a shuttlecock?", answer: "Badminton" },
{ question: "What sport is known as the gentleman's game?", answer: "Cricket" },
{ question: "What sport has the Olympics motto faster, higher, stronger?", answer: "Athletics" },
{ question: "What is the biggest tech company by market cap as of 2024?", answer: "Apple" },
{ question: "What is the largest social media platform by users?", answer: "Facebook" },
{ question: "What is the most streamed song on Spotify?", answer: "Blinding Lights" },
{ question: "What country has the most people?", answer: "India" },
{ question: "What country has the most time zones?", answer: "France" },
{ question: "What country produces the most coffee?", answer: "Brazil" },
{ question: "What is the hottest chili in the world?", answer: "Carolina Reaper" },
{ question: "What is the largest coral reef system?", answer: "Great Barrier Reef" },
{ question: "What animal is known for its black and white stripes?", answer: "Zebra" },
{ question: "What animal can live both in water and on land?", answer: "Frog" },
{ question: "What animal is known as man's best friend?", answer: "Dog" },
{ question: "What is the main language spoken in Brazil?", answer: "Portuguese" },
{ question: "What is the most watched sport in the world?", answer: "Football" },
{ question: "What is the largest lake in the world by area?", answer: "Caspian Sea" },
{ question: "What is the capital of France?", answer: "Paris" },
{ question: "What is the largest ocean on Earth?", answer: "Pacific Ocean" },
{ question: "Who wrote 'Romeo and Juliet'?", answer: "William Shakespeare" },
{ question: "What is the smallest country in the world?", answer: "Vatican City" },
{ question: "How many continents are there?", answer: "7" },
{ question: "What is the longest river in the world?", answer: "Nile" },
{ question: "Who discovered penicillin?", answer: "Alexander Fleming" },
{ question: "What is the hardest natural substance on Earth?", answer: "Diamond" },
{ question: "In which year did the Titanic sink?", answer: "1912" },
{ question: "What is the currency of Japan?", answer: "Yen" },
{ question: "Who was the first man to walk on the moon?", answer: "Neil Armstrong" },
{ question: "What is the tallest mountain in the world?", answer: "Mount Everest" },
{ question: "Which planet is known as the Red Planet?", answer: "Mars" },
{ question: "What is the chemical symbol for gold?", answer: "Au" },
{ question: "Who painted the Sistine Chapel ceiling?", answer: "Michelangelo" },
{ question: "What is the largest desert in the world?", answer: "Antarctica" },
{ question: "How many bones are in the adult human body?", answer: "206" },
{ question: "Which country is home to the kangaroo?", answer: "Australia" },
{ question: "What is the speed of light?", answer: "299,792 kilometers per second" },
{ question: "Who invented the telephone?", answer: "Alexander Graham Bell" },
{ question: "What is the capital of Brazil?", answer: "Brasília" },
{ question: "Which element has the atomic number 1?", answer: "Hydrogen" },
{ question: "In which city is the Eiffel Tower located?", answer: "Paris" },
{ question: "What is the largest mammal in the world?", answer: "Blue whale" },
{ question: "Who wrote '1984'?", answer: "George Orwell" },
{ question: "What is the capital of Egypt?", answer: "Cairo" },
{ question: "Which country has the most population?", answer: "India" },
{ question: "What is the smallest planet in our solar system?", answer: "Mercury" },
{ question: "Who was the first president of the United States?", answer: "George Washington" },
{ question: "What is the main ingredient in guacamole?", answer: "Avocado" },
{ question: "In which year did World War II end?", answer: "1945" },
{ question: "What is the capital of Russia?", answer: "Moscow" },
{ question: "Which bird is known for its colorful feathers and ability to mimic sounds?", answer: "Parrot" },
{ question: "What is the largest organ in the human body?", answer: "Skin" },
{ question: "Who discovered gravity when an apple fell on his head?", answer: "Isaac Newton" },
{ question: "What is the capital of Canada?", answer: "Ottawa" },
{ question: "Which metal is liquid at room temperature?", answer: "Mercury" },
{ question: "How many Harry Potter books are there?", answer: "7" },
{ question: "What is the capital of Australia?", answer: "Canberra" },
{ question: "Which country is known as the Land of the Rising Sun?", answer: "Japan" },
{ question: "Who wrote 'Pride and Prejudice'?", answer: "Jane Austen" },
{ question: "What is the deepest point in the ocean?", answer: "Mariana Trench" },
{ question: "In which year was the first iPhone released?", answer: "2007" },
{ question: "What is the capital of South Africa?", answer: "Pretoria" },
{ question: "Which animal is the tallest in the world?", answer: "Giraffe" },
{ question: "Who painted 'The Starry Night'?", answer: "Vincent van Gogh" },
{ question: "What is the chemical symbol for water?", answer: "H2O" },
{ question: "Which planet has the most moons?", answer: "Saturn" },
{ question: "What is the capital of Italy?", answer: "Rome" },
{ question: "Who was the Greek god of the sea?", answer: "Poseidon" },
{ question: "What is the largest country by land area?", answer: "Russia" },
{ question: "In which country were the ancient pyramids built?", answer: "Egypt" },
{ question: "What is the capital of Argentina?", answer: "Buenos Aires" },
{ question: "Which famous scientist developed the theory of relativity?", answer: "Albert Einstein" },
{ question: "What is the most spoken language in the world?", answer: "Mandarin Chinese" },
{ question: "Who sang 'Bohemian Rhapsody'?", answer: "Queen" },
{ question: "What is the capital of Mexico?", answer: "Mexico City" },
{ question: "Which country invented pizza?", answer: "Italy" },
{ question: "What is the name of the fairy in Peter Pan?", answer: "Tinker Bell" },
{ question: "In which year did the Berlin Wall fall?", answer: "1989" },
{ question: "What is the capital of Thailand?", answer: "Bangkok" },
{ question: "Which element is diamond made of?", answer: "Carbon" },
{ question: "Who played Jack in Titanic?", answer: "Leonardo DiCaprio" },
{ question: "What is the capital of Sweden?", answer: "Stockholm" },
{ question: "Which animal is known as man's best friend?", answer: "Dog" },
{ question: "What is the longest bone in the human body?", answer: "Femur" },
{ question: "Who wrote 'The Great Gatsby'?", answer: "F. Scott Fitzgerald" },
{ question: "What is the capital of Peru?", answer: "Lima" },
{ question: "Which planet is closest to the Sun?", answer: "Mercury" },
{ question: "What is the largest island in the world?", answer: "Greenland" },
{ question: "Who discovered America in 1492?", answer: "Christopher Columbus" },
{ question: "What is the capital of Norway?", answer: "Oslo" },
{ question: "Which fruit is known as the 'king of fruits' in Asia?", answer: "Durian" },
{ question: "What is the currency of the United Kingdom?", answer: "Pound sterling" },
{ question: "Who painted 'Guernica'?", answer: "Pablo Picasso" },
{ question: "What is the capital of Chile?", answer: "Santiago" },
{ question: "Which country hosted the 2016 Summer Olympics?", answer: "Brazil" },
{ question: "What is the smallest bone in the human body?", answer: "Stapes" },
{ question: "Who was the first woman to win a Nobel Prize?", answer: "Marie Curie" },
{ question: "What is the capital of Kenya?", answer: "Nairobi" },
{ question: "Which gas makes up about 78% of Earth's atmosphere?", answer: "Nitrogen" },
{ question: "Who directed 'Jurassic Park'?", answer: "Steven Spielberg" },
{ question: "What is the capital of Portugal?", answer: "Lisbon" },
{ question: "Which mammal can fly?", answer: "Bat" },
{ question: "What is the largest volcano in the world?", answer: "Mauna Loa" },
{ question: "Who wrote 'To Kill a Mockingbird'?", answer: "Harper Lee" },
{ question: "What is the capital of Greece?", answer: "Athens" },
{ question: "Which country is home to the Great Barrier Reef?", answer: "Australia" },
{ question: "What is the main gas in Earth's atmosphere?", answer: "Nitrogen" },
{ question: "Who invented the light bulb?", answer: "Thomas Edison" },
{ question: "What is the capital of Turkey?", answer: "Ankara" },
{ question: "Which famous ship sank in 1912?", answer: "Titanic" },
{ question: "What is the largest species of shark?", answer: "Whale shark" },
{ question: "Who was the Egyptian queen famous for her relationships with Roman leaders?", answer: "Cleopatra" },
{ question: "What is the capital of New Zealand?", answer: "Wellington" },
{ question: "Which planet has rings around it?", answer: "Saturn" },
{ question: "What is the most consumed manufactured drink in the world?", answer: "Tea" },
{ question: "Who painted 'The Last Supper'?", answer: "Leonardo da Vinci" },
{ question: "What is the capital of Iceland?", answer: "Reykjavik" },
{ question: "Which country is known for the tango dance?", answer: "Argentina" },
// Super easy (20)
{ question: "What is the capital of India?", answer: "New Delhi" },
{ question: "What color are bananas when ripe?", answer: "Yellow" },
{ question: "How many days are in a week?", answer: "Seven" },
{ question: "What planet do we live on?", answer: "Earth" },
{ question: "How many wheels does a bicycle have?", answer: "Two" },
{ question: "Which animal barks?", answer: "Dog" },
{ question: "What do bees make?", answer: "Honey" },
{ question: "What is H2O?", answer: "Water" },
{ question: "How many minutes are in an hour?", answer: "Sixty" },
{ question: "What shape is a pizza usually?", answer: "Circle" },
{ question: "What is the capital of France?", answer: "Paris" },
{ question: "What gas do humans breathe in?", answer: "Oxygen" },
{ question: "How many letters are in the English alphabet?", answer: "Twenty six" },
{ question: "What do cows drink?", answer: "Water" },
{ question: "What is 2 + 2?", answer: "Four" },
{ question: "What fruit keeps the doctor away?", answer: "Apple" },
{ question: "What is the opposite of hot?", answer: "Cold" },
{ question: "What animal gives milk?", answer: "Cow" },
{ question: "What is the color of the sky on a clear day?", answer: "Blue" },
{ question: "What do you call frozen water?", answer: "Ice" },

// Medium (60)
{ question: "What is the largest ocean on Earth?", answer: "Pacific Ocean" },
{ question: "Who wrote Harry Potter?", answer: "J. K. Rowling" },
{ question: "What is the tallest mountain in the world?", answer: "Mount Everest" },
{ question: "What is the capital of Australia?", answer: "Canberra" },
{ question: "What is the fastest land animal?", answer: "Cheetah" },
{ question: "Who painted The Starry Night?", answer: "Vincent van Gogh" },
{ question: "Who discovered penicillin?", answer: "Alexander Fleming" },
{ question: "What is the largest internal organ in the human body?", answer: "Liver" },
{ question: "What gas do plants breathe in?", answer: "Carbon dioxide" },
{ question: "How many continents are there?", answer: "Seven" },
{ question: "What is the hardest natural substance?", answer: "Diamond" },
{ question: "What is the currency of Japan?", answer: "Yen" },
{ question: "Where is the Taj Mahal located?", answer: "Agra" },
{ question: "Which planet is known as the red planet?", answer: "Mars" },
{ question: "What is the longest river in the world?", answer: "Nile" },
{ question: "What is the chemical symbol for gold?", answer: "Au" },
{ question: "What animal is the largest mammal?", answer: "Blue whale" },
{ question: "Which country invented pizza?", answer: "Italy" },
{ question: "Which country is famous for pyramids?", answer: "Egypt" },
{ question: "How many players are on a cricket team on the field?", answer: "Eleven" },
{ question: "What is the capital of Brazil?", answer: "Brasilia" },
{ question: "Which bird cannot fly?", answer: "Ostrich" },
{ question: "Which continent is the hottest?", answer: "Africa" },
{ question: "What is the main language spoken in Brazil?", answer: "Portuguese" },
{ question: "What sport uses a shuttlecock?", answer: "Badminton" },
{ question: "What sport is known as the gentleman's game?", answer: "Cricket" },
{ question: "In which city is Big Ben located?", answer: "London" },
{ question: "Which country produces the most coffee?", answer: "Brazil" },
{ question: "What is the largest desert in the world?", answer: "Sahara Desert" },
{ question: "What is the hottest planet in the solar system?", answer: "Venus" },
{ question: "Which ocean is the smallest?", answer: "Arctic Ocean" },
{ question: "Which planet has rings?", answer: "Saturn" },
{ question: "What metal is liquid at room temperature?", answer: "Mercury" },
{ question: "Which natural disaster is measured with a Richter scale?", answer: "Earthquake" },
{ question: "What do you call a baby kangaroo?", answer: "Joey" },
{ question: "Who was the first man on the Moon?", answer: "Neil Armstrong" },
{ question: "What year did World War II end?", answer: "1945" },
{ question: "Who is known as the father of computers?", answer: "Charles Babbage" },
{ question: "Which organ pumps blood through the body?", answer: "Heart" },
{ question: "What organ controls the body?", answer: "Brain" },
{ question: "What is the capital of Italy?", answer: "Rome" },
{ question: "What is the capital of Canada?", answer: "Ottawa" },
{ question: "What is the currency of the UK?", answer: "Pound" },
{ question: "What country has the most people?", answer: "India" },
{ question: "What is the closest star to Earth?", answer: "Sun" },
{ question: "Which planet is closest to the Sun?", answer: "Mercury" },
{ question: "Which animal is known for black and white stripes?", answer: "Zebra" },
{ question: "What is the national bird of the USA?", answer: "Bald eagle" },
{ question: "What is the most visited country in the world?", answer: "France" },
{ question: "What is the capital of Germany?", answer: "Berlin" },
{ question: "What is the longest bone in the human body?", answer: "Femur" },
{ question: "What is the largest island in the world?", answer: "Greenland" },
{ question: "Which sea creature has eight legs?", answer: "Octopus" },
{ question: "Which bird is known for its dance?", answer: "Peacock" },
{ question: "What is the main ingredient in bread?", answer: "Flour" },
{ question: "Which city is also known as the big apple?", answer: "New York City" },
{ question: "How many teeth does an adult human usually have?", answer: "Thirty two" },
{ question: "What is the currency of China?", answer: "Yuan" },
{ question: "Which country hosted the 2016 Olympics?", answer: "Brazil" },
{ question: "What is the largest coral reef system?", answer: "Great Barrier Reef" },
{ question: "Which country has the most time zones?", answer: "France" },
{ question: "Which country is known as the land of the rising sun?", answer: "Japan" },
{ question: "Which continent is the largest by area?", answer: "Asia" },
{ question: "What do you call molten rock that erupts from a volcano?", answer: "Lava" },
{ question: "What animal is known as man's best friend?", answer: "Dog" }, 

// Super hard (20)
{ question: "What is the longest word in the English dictionary?", answer: "Pneumonoultramicroscopicsilicovolcanoconiosis" },
{ question: "What element has the highest melting point?", answer: "Tungsten" },
{ question: "What is the rarest blood type?", answer: "AB negative" },
{ question: "What is the scientific name for the study of mushrooms?", answer: "Mycology" },
{ question: "What is the deepest point in the ocean?", answer: "Challenger Deep" },
{ question: "What is the only metal that is not silver, gray, or metallic?", answer: "Gold" },
{ question: "What is the most abundant element in the universe?", answer: "Hydrogen" },
{ question: "Which mathematician is known for the incompleteness theorems?", answer: "Kurt Godel" },
{ question: "Which scientist discovered the law of planetary motion?", answer: "Johannes Kepler" },
{ question: "What is the speed of light in meters per second?", answer: "299792458" },
{ question: "What is the smallest bone in the human body?", answer: "Stapes" },
{ question: "Which empire built Machu Picchu?", answer: "Inca Empire" },
{ question: "What is the oldest written language still used today?", answer: "Chinese" },
{ question: "Who wrote the ancient text Arthashastra?", answer: "Chanakya" },
{ question: "What is the second smallest country in the world?", answer: "Monaco" },
{ question: "What is the chemical formula for table salt?", answer: "NaCl" },
{ question: "Which galaxy is closest to the Milky Way?", answer: "Andromeda" },
{ question: "Which physicist is known for the uncertainty principle?", answer: "Werner Heisenberg" },
{ question: "What is the name of the supercontinent that existed 300 million years ago?", answer: "Pangaea" },
{ question: "Who first proposed the heliocentric model?", answer: "Nicolaus Copernicus" },
{ question: "What color is the sky on a clear day?", answer: "Blue" },
{ question: "How many legs does a spider have?", answer: "8" },
{ question: "What animal is known as the 'King of the Jungle'?", answer: "Lion" },
{ question: "In which hand does the Statue of Liberty hold the torch?", answer: "Right" },
{ question: "What is the name of the fairy in Peter Pan?", answer: "Tinker Bell" },
{ question: "How many days are in a week?", answer: "7" },
{ question: "What fruit is yellow and curved?", answer: "Banana" },
{ question: "What do you call a baby dog?", answer: "Puppy" },
{ question: "Which Disney movie features a character named Elsa?", answer: "Frozen" },
{ question: "What color is a school bus in the United States?", answer: "Yellow" },
{ question: "How many players are on a soccer team on the field?", answer: "11" },
{ question: "What is the name of Mickey Mouse's dog?", answer: "Pluto" },
{ question: "What is the hottest continent on Earth?", answer: "Africa" },
{ question: "What gas do plants breathe in that humans breathe out?", answer: "Carbon dioxide" },
{ question: "What is the biggest ocean in the world?", answer: "Pacific Ocean" },
{ question: "What animal is Pepé Le Pew from Looney Tunes?", answer: "Skunk" },
{ question: "What is the name of the toy cowboy in Toy Story?", answer: "Woody" },
{ question: "How many sides does a triangle have?", answer: "3" },
{ question: "What do bees make?", answer: "Honey" },
{ question: "What color are Smurfs?", answer: "Blue" },

// Medium difficulty (60 questions)
{ question: "What is the capital of France?", answer: "Paris" },
{ question: "Who painted the Mona Lisa?", answer: "Leonardo da Vinci" },
{ question: "What is the largest planet in our solar system?", answer: "Jupiter" },
{ question: "In which year did the Titanic sink?", answer: "1912" },
{ question: "What is the currency of Japan?", answer: "Yen" },
{ question: "Who was the first person to walk on the moon?", answer: "Neil Armstrong" },
{ question: "What is the longest river in the world?", answer: "Nile" },
{ question: "Which country is home to the kangaroo?", answer: "Australia" },
{ question: "What is the chemical symbol for gold?", answer: "Au" },
{ question: "How many bones are in the adult human body?", answer: "206" },
{ question: "Who wrote '1984'?", answer: "George Orwell" },
{ question: "What is the capital of Brazil?", answer: "Brasília" },
{ question: "Which planet is known as the Red Planet?", answer: "Mars" },
{ question: "What is the hardest natural substance on Earth?", answer: "Diamond" },
{ question: "Who discovered penicillin?", answer: "Alexander Fleming" },
{ question: "What is the tallest mountain in the world?", answer: "Mount Everest" },
{ question: "In which year did World War II end?", answer: "1945" },
{ question: "What is the capital of Egypt?", answer: "Cairo" },
{ question: "Which element has the atomic number 1?", answer: "Hydrogen" },
{ question: "What is the largest mammal in the world?", answer: "Blue whale" },
{ question: "Who painted 'The Starry Night'?", answer: "Vincent van Gogh" },
{ question: "What is the capital of Canada?", answer: "Ottawa" },
{ question: "How many Harry Potter books are there?", answer: "7" },
{ question: "Which country is known as the Land of the Rising Sun?", answer: "Japan" },
{ question: "What is the capital of Italy?", answer: "Rome" },
{ question: "Who wrote 'Pride and Prejudice'?", answer: "Jane Austen" },
{ question: "What is the deepest ocean trench?", answer: "Mariana Trench" },
{ question: "Which famous scientist developed the theory of relativity?", answer: "Albert Einstein" },
{ question: "What is the capital of Australia?", answer: "Canberra" },
{ question: "Which country invented pizza?", answer: "Italy" },
{ question: "In which year did the Berlin Wall fall?", answer: "1989" },
{ question: "What is the largest country by land area?", answer: "Russia" },
{ question: "Who was the first President of the United States?", answer: "George Washington" },
{ question: "What is the capital of Thailand?", answer: "Bangkok" },
{ question: "Which planet has the most moons?", answer: "Saturn" },
{ question: "What is the currency of the United Kingdom?", answer: "Pound sterling" },
{ question: "Who painted 'The Last Supper'?", answer: "Leonardo da Vinci" },
{ question: "What is the capital of Argentina?", answer: "Buenos Aires" },
{ question: "Which animal is the tallest in the world?", answer: "Giraffe" },
{ question: "What is the chemical symbol for water?", answer: "H₂O" },
{ question: "Who wrote 'To Kill a Mockingbird'?", answer: "Harper Lee" },
{ question: "What is the capital of Portugal?", answer: "Lisbon" },
{ question: "Which country hosted the 2016 Summer Olympics?", answer: "Brazil" },
{ question: "What is the largest desert in the world?", answer: "Antarctica" },
{ question: "Who invented the telephone?", answer: "Alexander Graham Bell" },
{ question: "What is the capital of South Africa?", answer: "Pretoria (administrative)" },
{ question: "Which bird is famous for laying the largest eggs?", answer: "Ostrich" },
{ question: "What is the smallest country in the world by land area?", answer: "Vatican City" },
{ question: "Who directed 'Jaws'?", answer: "Steven Spielberg" },
{ question: "What is the capital of Iceland?", answer: "Reykjavík" },
{ question: "Which metal is liquid at room temperature?", answer: "Mercury" },
{ question: "What is the most spoken language in the world?", answer: "Mandarin Chinese" },
{ question: "Who was the Greek god of the sea?", answer: "Poseidon" },
{ question: "What is the capital of New Zealand?", answer: "Wellington" },
{ question: "Which element is diamond made of?", answer: "Carbon" },
{ question: "What is the largest island in the world?", answer: "Greenland" },
{ question: "Who discovered America in 1492?", answer: "Christopher Columbus" },
{ question: "What is the capital of Norway?", answer: "Oslo" },
{ question: "Which country is home to the Great Barrier Reef?", answer: "Australia" },
{ question: "What is the main ingredient in hummus?", answer: "Chickpeas" },
{ question: "Who was the first woman to fly solo across the Atlantic?", answer: "Amelia Earhart" },

// Super hard (20 questions)
{ question: "What is the only letter that does not appear on the periodic table?", answer: "J" },
{ question: "Which country has the world's oldest continuously operating university?", answer: "Morocco (University of Al-Qarawiyyin, founded 859 AD)" },
{ question: "What is the dot over the lowercase letters i and j called?", answer: "Tittle" },
{ question: "Which planet has a day longer than its year?", answer: "Venus" },
{ question: "In what year was the first successful human heart transplant performed?", answer: "1967" },
{ question: "What is the only mammal capable of true sustained flight?", answer: "Bat" },
{ question: "Which country’s flag is the only one that is not rectangular or square?", answer: "Nepal" },
{ question: "What is the technical term for the fear of long words?", answer: "Hippopotomonstrosesquippedaliophobia" },
{ question: "Which element has the longest name in the periodic table?", answer: "Rutherfordium" },
{ question: "What is the only English word that ends with the letters 'mt'?", answer: "Dreamt" },
{ question: "Which African country was never colonized by a European power?", answer: "Ethiopia" },
{ question: "What is the shortest war in history, lasting only 38 minutes?", answer: "Anglo-Zanzibar War (1896)" },
{ question: "Which country has the most deserts in the world?", answer: "Antarctica (technically one massive desert)" },
{ question: "What gas, discovered on the sun before Earth, is the second most abundant element in the universe?", answer: "Helium" },
{ question: "Which king was the first to use a mobile phone?", answer: "King Harald V of Norway" },
{ question: "What is the only letter not used in any U.S. state name?", answer: "Q" },
{ question: "In which country is the world’s highest waterfall, Angel Falls?", answer: "Venezuela" },
{ question: "What is the name of the shortest bone in the human body?", answer: "Stapes" },
{ question: "Which language has the most words (according to dictionary entries)?", answer: "Korean" },
{ question: "What is the only food that cannot go bad?", answer: "Honey" },
  { question: "What is the capital city of France?", answer: "Paris" },
  { question: "What is the largest land animal in North America?", answer: "Bison" },
  { question: "How many seconds are in a minute?", answer: "60" },
  { question: "What primary color is mixed with yellow to make green?", answer: "Blue" },
  { question: "What is the boiling point of water at sea level in Fahrenheit?", answer: "212°F" },
  { question: "What is the currency of Japan?", answer: "Yen" },
  { question: "Which planet is known for its rings?", answer: "Saturn" },
  { question: "What do you use to write on a chalkboard?", answer: "Chalk" },
  { question: "What is the name of the wizard in 'The Lord of the Rings'?", answer: "Gandalf" },
  { question: "What country is geographically the largest in the world?", answer: "Russia" },
  { question: "Who was the first President of the United States?", answer: "George Washington" },
  { question: "What is the young of a sheep called?", answer: "Lamb" },
  { question: "What is the common name for the smallest prime number?", answer: "Two" },
  { question: "What is the color of a school bus?", answer: "Yellow" },
  { question: "Which large cat is known for its black stripes?", answer: "Tiger" },
  { question: "What month comes after March?", answer: "April" },
  { question: "How many days are in a regular year?", answer: "365" },
  { question: "What is the opposite of 'hot'?", answer: "Cold" },
  { question: "What is the main ingredient in bread?", answer: "Flour" },
  { question: "What number follows four?", answer: "Five" },
  { question: "Who painted 'Starry Night'?", answer: "Vincent van Gogh" },
  { question: "What gas do plants absorb from the atmosphere?", answer: "Carbon Dioxide" },
  { question: "What literary device is characterized by an exaggeration of statements for emphasis?", answer: "Hyperbole" },
  { question: "What is the primary function of the mitochondria in a cell?", answer: "Energy Production (ATP)" },
  { question: "What European city hosted the Summer Olympics in 1992?", answer: "Barcelona" },
  { question: "What is the chemical symbol for Tungsten?", answer: "W" },
  { question: "What is the name of the deepest point in the Earth's oceans?", answer: "Challenger Deep" },
  { question: "Which author wrote the dystopian novel '1984'?", answer: "George Orwell" },
  { question: "What is the capital of Australia?", answer: "Canberra" },
  { question: "What is the only mammal capable of true flight?", answer: "Bat" },
  { question: "What country is the origin of the martial art Taekwondo?", answer: "South Korea" },
  { question: "What is the value of $\\pi$ (pi) rounded to two decimal places?", answer: "3.14" },
  { question: "Who is generally credited with inventing the light bulb?", answer: "Thomas Edison" },
  { question: "What is the longest river in the world?", answer: "Nile River" },
  { question: "In the game of chess, which piece can only move diagonally?", answer: "Bishop" },
  { question: "What is the primary language spoken in Egypt?", answer: "Arabic" },
  { question: "What famous document begins with the words, 'We the People...'?", answer: "The US Constitution" },
  { question: "What kind of star is our sun?", answer: "Yellow Dwarf (G-type main-sequence star)" },
  { question: "What is the highest mountain peak in North America?", answer: "Denali (Mount McKinley)" },
  { question: "Which Shakespeare play features the character Hamlet?", answer: "Hamlet" },
  { question: "What is the standard unit of measurement for electrical resistance?", answer: "Ohm" },
  { question: "What type of cloud is associated with thunderstorms and heavy rain?", answer: "Cumulonimbus" },
  { question: "What is the name of the first human-made satellite launched into space?", answer: "Sputnik 1" },
  { question: "What is the chemical formula for ammonia?", answer: "NH₃" },
  { question: "What is the fear of long words called?", answer: "Hippopotomonstrosesquippedaliophobia" },
  { question: "What famous treaty ended World War I?", answer: "Treaty of Versailles" },
  { question: "Which Roman emperor made Christianity the state religion?", answer: "Theodosius I" },
  { question: "What is the term for the outer layer of the sun's atmosphere, visible during a total solar eclipse?", answer: "Corona" },
  { question: "What is the collective noun for a group of owls?", answer: "A Parliament" },
  { question: "What year was the popular video game 'Minecraft' officially released?", answer: "2011" },
  { question: "Which German mathematician is credited with the development of calculus independently of Isaac Newton?", answer: "Gottfried Wilhelm Leibniz" },
  { question: "What is the process by which a solid turns directly into a gas, bypassing the liquid phase?", answer: "Sublimation" },
  { question: "What is the deepest lake in the world?", answer: "Lake Baikal" },
  { question: "What author created the characters Sherlock Holmes and Dr. Watson?", answer: "Sir Arthur Conan Doyle" },
  { question: "What does NATO stand for?", answer: "North Atlantic Treaty Organization" },
  { question: "What is the largest country in South America by area?", answer: "Brazil" },
  { question: "What is the phenomenon called when a magnetic field reverses its polarity?", answer: "Geomagnetic Reversal" },
  { question: "What element is denoted by the atomic number 6?", answer: "Carbon" },
  { question: "What is the national flower of the Netherlands?", answer: "Tulip" },
  { question: "In music, what is the term for a note sustained or repeated beneath the melody?", answer: "Pedal Point (or Drone)" },
  { question: "What chemical compound is responsible for the red color in blood?", answer: "Hemoglobin" },
  { question: "Which country is the world's leading exporter of crude oil?", answer: "Saudi Arabia" },
  { question: "What type of volcano is characterized by broad, gently sloping sides?", answer: "Shield Volcano" },
  { question: "What is the chemical symbol for Silver?", answer: "Ag" },
  { question: "What is the technical term for the study of mushrooms?", answer: "Mycology" },
  { question: "Who directed the film 'Pulp Fiction'?", answer: "Quentin Tarantino" },
  { question: "What is the most widely spoken language in the world by native speakers?", answer: "Mandarin Chinese" },
  { question: "What does the 'G' stand for in 5G wireless technology?", answer: "Generation" },
  { question: "What is the term for a prolonged period of abnormally low rainfall?", answer: "Drought" },
  { question: "What is the square root of 144?", answer: "12" },
  { question: "What is the name of the main antagonist in the Harry Potter series?", answer: "Lord Voldemort" },
  { question: "What is the capital of Thailand?", answer: "Bangkok" },
  { question: "What type of tissue connects muscle to bone?", answer: "Tendon" },
  { question: "In Roman mythology, who is the god of war?", answer: "Mars" },
  { question: "What European mountain range separates France and Spain?", answer: "Pyrenees" },
  { question: "What does the acronym 'HTML' stand for?", answer: "HyperText Markup Language" },
  { question: "What is the smallest continent by land area?", answer: "Australia (or Oceania)" },
  { question: "What is the name of the dog in Disney's 'The Little Mermaid'?", answer: "Max" },
  { question: "In what year did the Titanic sink?", answer: "1912" },
  { question: "What is the SI unit for force?", answer: "Newton" },
  { question: "Which of the seven wonders of the ancient world is the only one still largely intact?", answer: "Great Pyramid of Giza" },
  { question: "What is the term for the transfer of heat through molecular collision?", answer: "Conduction" },
  { question: "What is the name of the ancient Greek philosopher who was the teacher of Alexander the Great?", answer: "Aristotle" },
  { question: "Who was the Greek goddess of wisdom and warfare?", answer: "Athena" },
  { question: "Which gas is responsible for the odor often associated with natural gas leaks (added for safety)?", answer: "Mercaptan (Methanethiol or Ethanethiol)" },
  { question: "What 17th-century conflict is known as the 'War of the Three Kingdoms'?", answer: "English Civil War" },
  { question: "What is the name of the physical property that describes a fluid's resistance to flow?", answer: "Viscosity" },
  { question: "What is the unit of measure for the amount of substance in the International System of Units (SI)?", answer: "Mole" },
  { question: "What is the term for a word that is spelled the same forwards and backwards?", answer: "Palindrome" },
  { question: "Which German city is the headquarters of the European Central Bank?", answer: "Frankfurt" },
  { question: "What is the technical term for the process of aging wine in a wooden barrel?", answer: "Elevage" },
  { question: "What type of nuclear reaction powers the sun?", answer: "Nuclear Fusion" },
  { question: "Who was the only U.S. President to serve two non-consecutive terms?", answer: "Grover Cleveland" },
  { question: "What color is indigo on the visible light spectrum?", answer: "Blue-Violet" },
  { question: "What is the name of the famous 19th-century gold rush in Australia?", answer: "Victorian Gold Rush (or Ballarat Gold Rush)" },
  { question: "What is the study of birds called?", answer: "Ornithology" },
  { question: "What does the acronym 'DDT' stand for?", answer: "Dichlorodiphenyltrichloroethane" },
  { question: "What is the name of the current epoch of the Quaternary period, which began approximately 11,700 years ago?", answer: "Holocene" },
  { question: "Which Renaissance artist is known for the statue 'David'?", answer: "Michelangelo" },
  { question: "What is the main component of natural gas?", answer: "Methane" },
  { question: "What is the name of the first written code of law, created in ancient Mesopotamia?", answer: "Code of Hammurabi" },
{ question: "What is the capital of India?", answer: "New Delhi" },
{ question: "Who directed the movie Interstellar?", answer: "Christopher Nolan" },
{ question: "Which animal is known as the king of the jungle?", answer: "Lion" },
{ question: "In Greek myth, who tamed Pegasus and killed the Chimera?", answer: "Bellerophon" },
{ question: "What is the largest continent by area?", answer: "Asia" },
{ question: "Which Indian director made Pather Panchali?", answer: "Satyajit Ray" },
{ question: "How many continents are there?", answer: "Seven" },
{ question: "Who is the Norse god of thunder?", answer: "Thor" },
{ question: "What is the chemical symbol for water?", answer: "H2O" },
{ question: "Which river flows through Cairo?", answer: "Nile" },
{ question: "Which bird is a symbol of peace?", answer: "Dove" },
{ question: "Who wrote the Ramayana according to tradition?", answer: "Valmiki" },
{ question: "What is the capital of Australia?", answer: "Canberra" },
{ question: "Which movie won Best Picture at the 2020 Oscars?", answer: "Parasite" },
{ question: "Which planet is known as the Red Planet?", answer: "Mars" },
{ question: "In Hindu myth, who is the monkey god who helped Rama?", answer: "Hanuman" },
{ question: "What is the highest mountain in Africa?", answer: "Mount Kilimanjaro" },
{ question: "Who played Forrest Gump in the movie Forrest Gump?", answer: "Tom Hanks" },
{ question: "What is the largest ocean on Earth?", answer: "Pacific Ocean" },
{ question: "Which Greek god is the ruler of the underworld?", answer: "Hades" },
{ question: "What language is primarily spoken in Brazil?", answer: "Portuguese" },
{ question: "Which film composer wrote the score for The Good, the Bad and the Ugly?", answer: "Ennio Morricone" },
{ question: "What is the smallest prime number?", answer: "2" },
{ question: "Which Norse figure guards the bridge to Asgard?", answer: "Heimdall" },
{ question: "Which country has the largest population?", answer: "China" },
{ question: "Which Indian actor starred in the movie Lagaan?", answer: "Aamir Khan" },
{ question: "What is the capital of France?", answer: "Paris" },
{ question: "Who is the king of the Greek gods?", answer: "Zeus" },
{ question: "Which US state is the Grand Canyon in?", answer: "Arizona" },
{ question: "Which goddess sprang from Zeus' head fully armed?", answer: "Athena" },
{ question: "What is the longest river in South America?", answer: "Amazon River" },
{ question: "Which movie features the line, 'May the Force be with you'?", answer: "Star Wars" },
{ question: "How many seasons does the Earth have?", answer: "Four" },
{ question: "In Japanese myth, who is the sun goddess?", answer: "Amaterasu" },
{ question: "Which country is Istanbul located in?", answer: "Turkey" },
{ question: "Who directed the Indian film Mother India (1957)?", answer: "Mehboob Khan" },
{ question: "What does GPS stand for?", answer: "Global Positioning System" },
{ question: "Who is the Roman equivalent of the Greek god Zeus?", answer: "Jupiter" },
{ question: "Which mountain range separates Europe and Asia?", answer: "Ural Mountains" },
{ question: "Which actor played the Joker in The Dark Knight?", answer: "Heath Ledger" },
{ question: "What is the largest desert in the world (non polar)?", answer: "Sahara Desert" },
{ question: "In Maori myth, who fished up the North Island of New Zealand?", answer: "Māui" },
{ question: "Which city is the capital of Japan?", answer: "Tokyo" },
{ question: "Who choreographed the dance scenes in the movie La La Land?", answer: "Mandy Moore" },
{ question: "What is the currency of the United Kingdom?", answer: "Pound sterling" },
{ question: "Who is the mother of the god Apollo in Greek myth?", answer: "Leto" },
{ question: "Which country has the most time zones?", answer: "France" },
{ question: "Which Indian movie won the Palme d'Or at Cannes in 2008?", answer: "Slumdog Millionaire" },
{ question: "What is the capital of Canada?", answer: "Ottawa" },
{ question: "Which creature is half man, half bull in Greek myth?", answer: "Minotaur" },
{ question: "Which river runs through London?", answer: "Thames" },
{ question: "Who directed the film Pulp Fiction?", answer: "Quentin Tarantino" },
{ question: "What is the largest island in the world?", answer: "Greenland" },
{ question: "Which Hindu god is known as the destroyer?", answer: "Shiva" },
{ question: "Which country contains the city of Marrakech?", answer: "Morocco" },
{ question: "Which movie franchise features the character Indiana Jones?", answer: "Indiana Jones" },
{ question: "Which volcano famously erupted in AD 79 burying Pompeii?", answer: "Mount Vesuvius" },
{ question: "Who is the goddess of wisdom in Roman myth?", answer: "Minerva" },
{ question: "Which actor played the lead role in the movie Chak De! India?", answer: "Shah Rukh Khan" },
{ question: "What is the capital of Egypt?", answer: "Cairo" },
{ question: "Which Greek hero completed twelve labors?", answer: "Heracles" },
{ question: "Which mountain is the highest in the world above sea level?", answer: "Mount Everest" },
{ question: "Which movie is about a jazz pianist and an aspiring actress in Los Angeles?", answer: "La La Land" },
{ question: "Which sea lies between Saudi Arabia and Africa?", answer: "Red Sea" },
{ question: "Who is the trickster god in Norse myth who caused the death of Baldr?", answer: "Loki" },
{ question: "Which Indian epic features the Kurukshetra war?", answer: "Mahabharata" },
{ question: "Which country is known as the land of the rising sun?", answer: "Japan" },
{ question: "Which director is famous for long takes and made the film 1917?", answer: "Sam Mendes" },
{ question: "What is the capital of Argentina?", answer: "Buenos Aires" },
{ question: "In Greek myth, who flew too close to the sun?", answer: "Icarus" },
{ question: "Which ocean borders the west coast of India?", answer: "Indian Ocean" },
{ question: "Which composer wrote the music for the film The Lord of the Rings trilogy?", answer: "Howard Shore" },
{ question: "What is the deepest lake in the world?", answer: "Lake Baikal" },
{ question: "Which Mesopotamian hero searches for immortality in ancient myth?", answer: "Gilgamesh" },
{ question: "Which city is the capital of South Korea?", answer: "Seoul" },
{ question: "Who directed the Indian film The Lunchbox?", answer: "Ritesh Batra" },
{ question: "Which country has the most UNESCO World Heritage Sites?", answer: "Italy" },
{ question: "Which goddess in Hindu tradition is worshipped as the mother and fierce protector, often called Durga?", answer: "Durga" },
{ question: "Which film features the fictional continent of Wakanda?", answer: "Black Panther" },
{ question: "Which country is the island of Hokkaido part of?", answer: "Japan" },
{ question: "In Roman myth, who is the god of war?", answer: "Mars" },
{ question: "Which mountain range contains Mount Fuji?", answer: "None, Mount Fuji is a standalone volcanic peak" },
{ question: "Which movie director is known for the Tamil film Nayakan?", answer: "Mani Ratnam" },
{ question: "What is the capital of Spain?", answer: "Madrid" },
{ question: "Which creature in Norse myth will end the world by fighting Odin during Ragnarok?", answer: "Fenrir" },
{ question: "Which Indian festival celebrates the return of Lord Rama to Ayodhya?", answer: "Diwali" },
{ question: "Which European capital city is divided by the Danube and has Buda and Pest?", answer: "Budapest" },
{ question: "Which film earned Ang Lee an Oscar for Best Director for a martial arts drama in 2001?", answer: "Crouching Tiger, Hidden Dragon" },
{ question: "Which desert covers much of northern China and Mongolia?", answer: "Gobi Desert" },
{ question: "In Greek myth, who is the craftsman who made Pandora?", answer: "Hephaestus" },
{ question: "Which actor played the title role in the film Gandhi?", answer: "Ben Kingsley" },
{ question: "Which river forms part of the border between the United States and Mexico?", answer: "Rio Grande" },
{ question: "Which ancient Egyptian god has the head of a jackal and guided the dead?", answer: "Anubis" },
{ question: "Which Indian film industry is often called Tollywood for Telugu cinema?", answer: "Telugu film industry" },
{ question: "Which capital city is known as the City of a Hundred Spires?", answer: "Prague" },
{ question: "Which Greek god is associated with the sea?", answer: "Poseidon" },
{ question: "Which movie features a character named 'Vito Corleone'?", answer: "The Godfather" },
{ question: "Which is the longest mountain range in the world?", answer: "Andes" },
{ question: "Who is the author of the Norse myths collection in the Poetic Edda?", answer: "No single author, it is a compilation from oral tradition" },
{ question: "Which filmmaker created the Oscar winning film Slumdog Millionaire?", answer: "Danny Boyle" },
{ question: "What is the capital of New Zealand?", answer: "Wellington" },
{ question: "Which mythical bird dies in flames and is reborn from its ashes?", answer: "Phoenix" },
{ question: "Which actor won the Best Actor Oscar for the film The King's Speech?", answer: "Colin Firth" },
{ question: "Which strait separates Alaska from Russia?", answer: "Bering Strait" },
{ question: "In Hindu myth, who is the charioteer and guide of Arjuna in the Bhagavad Gita?", answer: "Krishna" },
{ question: "Which 1950s Japanese director made Seven Samurai?", answer: "Akira Kurosawa" },
{ question: "What is the capital of Ethiopia?", answer: "Addis Ababa" },
{ question: "Which Greek hero is famous for his cleverness and the Trojan Horse?", answer: "Odysseus" },
{ question: "Which film director made the movie Sholay?", answer: "Ramesh Sippy" },
{ question: "What is the deepest point in the world ocean called?", answer: "Challenger Deep" },
{ question: "Which goddess in Greek myth is associated with love and beauty?", answer: "Aphrodite" },
{ question: "Which movie is a biopic of boxer Muhammad Ali starring Will Smith?", answer: "Ali" },
{ question: "Which peninsula contains the countries of Spain and Portugal?", answer: "Iberian Peninsula" },
{ question: "Which ancient Indian emperor converted to Buddhism and spread it widely?", answer: "Ashoka" },
{ question: "Which recent global film winner for Best International Feature at the Oscars was from South Korea?", answer: "Parasite" },
{ question: "Which legendary Celtic warrior woman led the Iceni against Rome?", answer: "Boudica" },
{ question: "Which sea is the saltiest inland sea in the world, between Jordan and Israel?", answer: "Dead Sea" },
{ question: "Which Roman poet wrote the Aeneid?", answer: "Virgil" },
{ question: "Which actress starred as the lead in the Indian film Queen?", answer: "Kangana Ranaut" },
{ question: "Which large African lake is shared by Tanzania, Uganda, and Kenya?", answer: "Lake Victoria" },
{ question: "Which epic Greek poet is credited with the Iliad and the Odyssey?", answer: "Homer" },
{ question: "Which movie director is known for the film The Seventh Seal about chess with Death?", answer: "Ingmar Bergman" },
{ question: "Which strait connects the Black Sea and the Mediterranean Sea?", answer: "Bosporus Strait" },
{ question: "In Zoroastrianism, who is the spirit of evil?", answer: "Angra Mainyu" },
{ question: "Which animated Indian film studio produced Hanuman (2005)?", answer: "Percept Picture Company" },
// LANGUAGE / SPELLING / ETYMOLOGY
{ question: "What is the only English word that is still spelled the same when you remove four of its five letters?", answer: "Queue" }, // super hard
{ question: "Which word in English has the most definitions in the Oxford English Dictionary?", answer: "Set" }, // super hard
{ question: "What is the longest English word with only one vowel?", answer: "Strengths" }, // hard
{ question: "Which common English word used to mean 'to murder someone by cutting their throat'?", answer: "Assassinate" }, // hard
{ question: "What does the word 'trivia' originally mean in Latin?", answer: "Where three roads meet" }, // medium
{ question: "How do you correctly spell the past tense of 'lead' (the metal)?", answer: "Led" }, // medium
{ question: "Which English word comes from the Greek word meaning 'lazy'?", answer: "School" }, // medium
{ question: "What is the only English word that ends with the letters '-mt'?", answer: "Dreamt" }, // medium
{ question: "How many letters are in the longest word in English that doesn’t repeat any letter?", answer: "15 (uncopyrightables)" }, // hard

// SPORTS
{ question: "How many dimples does an average golf ball have?", answer: "336" }, // super hard
{ question: "Which country has won the most Olympic gold medals in history?", answer: "United States" }, // medium
{ question: "In which sport can you score a ‘hole in one’?", answer: "Golf" }, // super easy
{ question: "How many players are on a baseball team on the field?", answer: "9" }, // easy
{ question: "Which boxer was known as 'The Greatest' and 'The Louisville Lip'?", answer: "Muhammad Ali" }, // medium
{ question: "In tennis, what comes after deuce?", answer: "Advantage" }, // medium
{ question: "Which country invented the sport of curling?", answer: "Scotland" }, // hard

// MUSIC
{ question: "Which composer wrote only nine symphonies but is still considered one of the greatest?", answer: "Ludwig van Beethoven" }, // medium
{ question: "What is the only musical instrument played by Freddie Mercury on stage that wasn’t piano or vocals?", answer: "Tambourine" }, // hard
{ question: "Which band’s logo is a tongue sticking out?", answer: "The Rolling Stones" }, // easy
{ question: "How many strings does a standard violin have?", answer: "4" }, // easy
{ question: "Which 20th-century composer wrote 'The Rite of Spring,' which caused a riot at its 1913 premiere?", answer: "Igor Stravinsky" }, // hard

// MOVIES
{ question: "Which movie contains the line 'Here's looking at you, kid'?", answer: "Casablanca" }, // medium
{ question: "What is the highest-grossing animated movie of all time (as of 2025)?", answer: "The Lion King (2019)" }, // medium
{ question: "Which actor has won the most Academy Awards for Best Actor?", answer: "Daniel Day-Lewis (3)" }, // hard
{ question: "In which movie does Tom Hanks play a character named Forrest?", answer: "Forrest Gump" }, // easy
{ question: "Which 1994 movie has the famous line 'Life is like a box of chocolates'?", answer: "Forrest Gump" }, // easy

// POLITICS
{ question: "Who was the youngest elected U.S. president?", answer: "John F. Kennedy" }, // medium
{ question: "Which country has had only one female prime minister who served non-consecutive terms totaling over 11 years?", answer: "United Kingdom (Margaret Thatcher)" }, // hard
{ question: "How many members are in the U.S. Senate?", answer: "100" }, // easy

{ question: "What is the capital of India?", answer: "New Delhi" },
{ question: "What planet do we live on?", answer: "Earth" },
{ question: "What animal says meow?", answer: "Cat" },
{ question: "What gas do humans need to breathe?", answer: "Oxygen" },
{ question: "What food is made from milk?", answer: "Cheese" },
{ question: "What is 5 plus 5?", answer: "10" },
{ question: "What fruit is yellow and long?", answer: "Banana" },
{ question: "What is the tallest land animal?", answer: "Giraffe" },
{ question: "Which country is famous for sushi?", answer: "Japan" },
{ question: "What do bees make?", answer: "Honey" },
{ question: "Which animal is known as man's best friend?", answer: "Dog" },
{ question: "How many days are in a week?", answer: "Seven" },
{ question: "What is the closest star to Earth?", answer: "Sun" },
{ question: "What drink comes from coffee beans?", answer: "Coffee" },
{ question: "What color are carrots usually?", answer: "Orange" },
{ question: "Who is Mickey Mouse's dog?", answer: "Pluto" },
{ question: "What do cows drink?", answer: "Water" },
{ question: "What do you call frozen water?", answer: "Ice" },
{ question: "What is H2O?", answer: "Water" },
{ question: "What shape is a football?", answer: "Oval" },
{ question: "What is the largest ocean on Earth?", answer: "Pacific Ocean" },
{ question: "What is the main ingredient in bread?", answer: "Flour" },
{ question: "Who directed the movie Interstellar?", answer: "Christopher Nolan" },
{ question: "What is the chemical symbol for gold?", answer: "Au" },
{ question: "Which organ pumps blood through the body?", answer: "Heart" },
{ question: "Which animal is the largest mammal?", answer: "Blue whale" },
{ question: "What is the capital of Brazil?", answer: "Brasilia" },
{ question: "Who is the Greek god of the sea?", answer: "Poseidon" },
{ question: "Which food dish is from Italy and shaped like a circle?", answer: "Pizza" },
{ question: "Which city is the capital of Japan?", answer: "Tokyo" },
{ question: "What is the hardest natural substance?", answer: "Diamond" },
{ question: "What does GDP stand for?", answer: "Gross Domestic Product" },
{ question: "Where do kangaroos live?", answer: "Australia" },
{ question: "Which movie features the line I'll be back?", answer: "The Terminator" },
{ question: "Which river flows through Egypt?", answer: "Nile" },
{ question: "Which vitamin comes from sunlight?", answer: "Vitamin D" },
{ question: "What is the biggest planet in our solar system?", answer: "Jupiter" },
{ question: "Which animal can change color to hide?", answer: "Chameleon" },
{ question: "Who wrote Harry Potter?", answer: "J. K. Rowling" },
{ question: "Which sport uses a shuttlecock?", answer: "Badminton" },
{ question: "Which country has the city of Seoul?", answer: "South Korea" },
{ question: "What part of the plant carries water?", answer: "Stem" },
{ question: "What is the study of life called?", answer: "Biology" },
{ question: "Which actor played Iron Man?", answer: "Robert Downey Jr." },
{ question: "What is the most used social media app in the world?", answer: "Facebook" },
{ question: "Which organ helps us breathe?", answer: "Lungs" },
{ question: "Which bird is the fastest in a dive?", answer: "Peregrine falcon" },
{ question: "Which continent is the Sahara Desert on?", answer: "Africa" },
{ question: "Which film won Best Picture at the 2020 Oscars?", answer: "Parasite" },
{ question: "What does DNA stand for?", answer: "Deoxyribonucleic acid" },
{ question: "Which country eats the most rice?", answer: "China" },
{ question: "What is the currency of the United Kingdom?", answer: "Pound" },
{ question: "Which element has the symbol Fe?", answer: "Iron" },
{ question: "Who is the Norse god of thunder?", answer: "Thor" },
{ question: "What animal is known for black and white stripes?", answer: "Zebra" },
{ question: "Which movie features a floating feather in its opening scene?", answer: "Forrest Gump" },
{ question: "What is the hottest planet in the solar system?", answer: "Venus" },
{ question: "Which gas do plants release after photosynthesis?", answer: "Oxygen" },
{ question: "Which city is known as the Big Apple?", answer: "New York City" },
{ question: "What is the capital of South Korea?", answer: "Seoul" },
{ question: "Which country produces the most coffee?", answer: "Brazil" },
{ question: "Which fruit has seeds on the outside?", answer: "Strawberry" },
{ question: "Who is the father of economics?", answer: "Adam Smith" },
{ question: "Which animal lays the largest eggs?", answer: "Ostrich" },
{ question: "What body part has the smallest bones?", answer: "Ear" },
{ question: "Which movie features a ring that must be destroyed?", answer: "The Lord of the Rings" },
{ question: "Which Indian dish is made of rice and lentils cooked together?", answer: "Khichdi" },
{ question: "What does a meteorologist study?", answer: "Weather" },
{ question: "Which continent has the most countries?", answer: "Africa" },
{ question: "What is the main gas in the air we breathe?", answer: "Nitrogen" },
{ question: "Which sport is known as the gentleman's game?", answer: "Cricket" },
{ question: "Who is the Greek goddess of wisdom?", answer: "Athena" },
{ question: "Which organ cleans the blood?", answer: "Kidneys" },
{ question: "Who directed the movie Pulp Fiction?", answer: "Quentin Tarantino" },
{ question: "What do you call a young horse?", answer: "Foal" },
{ question: "Which country is famous for chocolate and watches?", answer: "Switzerland" },
{ question: "What is the main ingredient in guacamole?", answer: "Avocado" },
{ question: "What is the largest lake in Africa?", answer: "Lake Victoria" },
{ question: "Which group sang the song Bohemian Rhapsody?", answer: "Queen" },
{ question: "What does CPI stand for in economics?", answer: "Consumer Price Index" },
{ question: "Which blood cells fight infection?", answer: "White blood cells" },
{ question: "Which economist created the idea of creative destruction?", answer: "Joseph Schumpeter" },
{ question: "What is the scientific name for humans?", answer: "Homo sapiens" },
{ question: "Which hormone regulates blood sugar?", answer: "Insulin" },
{ question: "What is the only mammal that can fly?", answer: "Bat" },
{ question: "Which element has the highest melting point?", answer: "Tungsten" },
{ question: "Which country has the deepest lake in the world?", answer: "Russia" },
{ question: "Which thinker wrote The Wealth of Nations?", answer: "Adam Smith" },
{ question: "Which Greek hero killed the Chimera?", answer: "Bellerophon" },
{ question: "Which film won the first ever Academy Award for Best Picture?", answer: "Wings" },
{ question: "What is the rarest blood type?", answer: "AB negative" },
{ question: "Which enzyme starts starch digestion in the mouth?", answer: "Amylase" },
{ question: "Which animal has the most powerful bite force?", answer: "Saltwater crocodile" },
{ question: "Which spice is the most expensive by weight?", answer: "Saffron" },
{ question: "Which economic theory is linked with John Maynard Keynes?", answer: "Keynesian economics" },
{ question: "Which galaxy is on a crash path with the Milky Way?", answer: "Andromeda" },
{ question: "Which Norse creature will fight Odin at Ragnarok?", answer: "Fenrir" },
{ question: "Which film movement is known for long takes and realism in Italy in the 40s?", answer: "Italian neorealism" },
{ question: "Which bacteria causes tuberculosis?", answer: "Mycobacterium tuberculosis" },
{ question: "What is the deepest point in the ocean?", answer: "Challenger Deep" },
{ question: "Which food dish uses fermented soybeans and comes from Japan?", answer: "Natto" },
  { question: "What company started as an online bookstore in 1994?", answer: "Amazon" },
  { question: "What is the collective term for the initial amount of money provided to a startup to fund its first steps?", answer: "Seed funding" },
  { question: "Which major search engine's name is a misspelling of a mathematical term for the number 1 followed by 100 zeros?", answer: "Google" },
  { question: "Who co-founded Microsoft with Bill Gates?", answer: "Paul Allen" },
  { question: "What is the common term for a company's debut public sale of stock?", answer: "IPO (Initial Public Offering)" },
  { question: "Which social media platform was originally called 'Thefacebook'?", answer: "Facebook" },
  { question: "What brand is famous for the slogan 'Just Do It'?", answer: "Nike" },
  { question: "What car company's logo features a four-ring design?", answer: "Audi" },
  { question: "In business, what does the abbreviation 'CRM' stand for?", answer: "Customer Relationship Management" },
  { question: "What soft drink company has its headquarters in Atlanta, Georgia?", answer: "Coca-Cola" },
  { question: "Who founded the Virgin Group?", answer: "Richard Branson" },
  { question: "The acronym 'VC' in the startup world stands for what?", answer: "Venture Capital" },
  { question: "What company is known for its operating system named after a fruit?", answer: "Apple" },
  { question: "What is the formal term for an early-stage startup valued at over $1 billion?", answer: "Unicorn" },
  { question: "Which company is the parent of Instagram and WhatsApp?", answer: "Meta Platforms (formerly Facebook)" },
  { question: "What is the name of the Swedish company that is the world's largest furniture retailer?", answer: "IKEA" },
  { question: "What popular streaming service was originally a mail-order DVD rental business?", answer: "Netflix" },
  { question: "What professional networking site was founded by Reid Hoffman?", answer: "LinkedIn" },
  { question: "What term is used for a market structure where a single company dominates?", answer: "Monopoly" },
  { question: "What beverage company owns the brand Mountain Dew?", answer: "PepsiCo" },
  { question: "What is the typical amount of equity a startup founder gives up during a Series A funding round?", answer: "20% to 25%" },
  { question: "Who was the CEO of Hewlett-Packard (HP) who famously bought Compaq in 2002?", answer: "Carly Fiorina" },
  { question: "What is the term for a clause in a shareholder agreement that prohibits founders from selling their shares for a specified period after an IPO?", answer: "Lock-up period" },
  { question: "What is the 'Rule of 40' commonly used to assess the health of a SaaS (Software as a Service) company?", answer: "Revenue growth rate plus profit margin should equal 40% or more" },
  { question: "The valuation method that uses discounted future cash flows is commonly referred to by what three-letter acronym?", answer: "DCF (Discounted Cash Flow)" },
  { question: "Who founded the Chinese e-commerce giant Alibaba?", answer: "Jack Ma" },
  { question: "What company, now a major player in cloud computing, was once named Computing-Tabulating-Recording Company?", answer: "IBM" },
  { question: "What financial ratio is calculated by dividing a company's market capitalization by its total annual revenue?", answer: "Price-to-Sales Ratio (P/S)" },
  { question: "Which company's founders famously received a check for $100,000 from Sun Microsystems as part of a settlement that led to its name?", answer: "Google" },
  { question: "What is the official term for the process of moving a company's headquarters or registration to a different, often lower-tax, jurisdiction?", answer: "Inversion" },
  { question: "What German car company owns the Bentley, Lamborghini, and Ducati brands?", answer: "Volkswagen Group" },
  { question: "What is the name of the private equity firm that acquired Dell in 2013, taking it private?", answer: "Silver Lake Partners" },
  { question: "What is the standard legal term for a written document used to govern the relationship between co-founders?", answer: "Founder's Agreement" },
  { question: "What is the primary difference between a Convertible Note and a SAFE (Simple Agreement for Future Equity)?", answer: "A Convertible Note is debt that accrues interest; a SAFE is not debt and does not accrue interest" },
  { question: "In the 1990s, what was the common nickname for the practice of selling tech stocks rapidly after an IPO for a quick profit?", answer: "Flipping" },
  { question: "What company, founded by Masayoshi Son, is known for its massive Vision Fund that invests heavily in late-stage tech startups?", answer: "SoftBank" },
  { question: "What is the term for a market in which investors' pessimism causes stock prices to fall?", answer: "Bear Market" },
  { question: "What is the legal structure typically preferred by early-stage US startups for ease of raising venture capital?", answer: "C-Corporation (C-Corp)" },
  { question: "What is the financial metric that measures the total revenue a company can expect to earn from a single customer relationship over time?", answer: "Lifetime Value (LTV)" },
  { question: "Which major computer operating system was originally named 'QDOS' (Quick and Dirty Operating System)?", answer: "MS-DOS" },
  { question: "What is the name of the financial document that describes a company's business, financials, and risks, issued during an IPO?", answer: "Prospectus (or S-1 Filing)" },
  { question: "What business model involves generating revenue by charging a fee for access to a product or service over a set period?", answer: "Subscription model" },
  { question: "What is the largest publicly traded company in the world by market capitalization (as of late 2024)?", answer: "Microsoft" },
  { question: "What company did Elon Musk co-found before Tesla and SpaceX that was later sold to PayPal?", answer: "X.com (merged with Confinity to form PayPal)" },
  { question: "What is the minimum viable product often referred to by the acronym?", answer: "MVP" },
  { question: "What is the common term for the legal agreement that protects founders from immediate dilution by giving them more shares later if targets are missed?", answer: "Anti-dilution clause (or ratchet)" },
  { question: "What metric is calculated by subtracting the cost of acquiring a customer from the customer's lifetime value (LTV)?", answer: "LTV:CAC ratio (or ROI)" },
  { question: "What is the name of the investment firm that created the first index fund?", answer: "Vanguard" },
  { question: "What 1990s video game company famously developed the characters Mario and Link?", answer: "Nintendo" },
  { question: "What is the term for the process of a venture capital firm selling its stake in a startup, typically through an acquisition or IPO?", answer: "Exit" },
  { question: "What automotive company was founded by Ferruccio in 1963?", answer: "Lamborghini" },
  { question: "What famous investment bank was founded by Henry and Marcus Goldman?", answer: "Goldman Sachs" },
  { question: "What is the primary purpose of a 'data room' during the due diligence phase of an acquisition?", answer: "To securely share sensitive company documents with the buyer/investor" },
  { question: "What accounting principle requires companies to record revenues and expenses when they occur, not when cash is exchanged?", answer: "Accrual basis accounting" },
  { question: "What term describes the process where a company outsources key internal functions to another firm?", answer: "Business Process Outsourcing (BPO)" },
  { question: "Which company, now a major cloud provider, originally sold books and music online?", answer: "Amazon (AWS)" },
  { question: "What metric measures the percentage of users who stop using a product or service over a given period?", answer: "Churn rate" },
  { question: "What does the 'A' in 'GAFA' (a tech acronym) stand for?", answer: "Amazon" },
  { question: "Which company, founded in 1908 in Detroit, revolutionized manufacturing with the assembly line?", answer: "Ford Motor Company" },
  { question: "What term is used for the legal protection of artistic and literary works?", answer: "Copyright" },
  { question: "What European beverage giant owns brands like Heineken and Amstel?", answer: "Heineken N.V." },
  { question: "What is the common name for the provision that prevents a VC firm's investment from being valued less than a previous round's valuation?", answer: "Ratchet (or Full-Ratchet)" },
  { question: "What is the maximum number of shareholders a company can have to be classified as an S-Corporation in the US?", answer: "100" },
  { question: "What is the primary function of a lead investor in a venture capital round?", answer: "Sets the valuation and term sheet" },
  { question: "What company developed the first widely successful graphical user interface (GUI) and mouse, commercializing technology from Xerox PARC?", answer: "Apple (Macintosh)" },
  { question: "What is the common name for the highly liquid assets that companies hold, such as cash and short-term investments?", answer: "Working capital" },
  { question: "What famous economist developed the theory of 'Creative Destruction' where new innovation replaces outdated practices?", answer: "Joseph Schumpeter" },
  { question: "What is the term for a market where a small number of sellers control the supply of a commodity or service?", answer: "Oligopoly" },
  { question: "What is the four-letter stock market ticker symbol for Apple Inc.?", answer: "AAPL" },
  { question: "What is the legal and financial process of liquidating an insolvent startup?", answer: "Bankruptcy" },
  { question: "What is the financial metric that calculates how many times a company has to cover its debt interest payments with its earnings?", answer: "Interest Coverage Ratio" },
  { question: "In the 1990s, what term was used for the speculative bubble in internet-based companies?", answer: "Dot-com Bubble" },
  { question: "What is the common term for the shares reserved for future employees and advisors in a startup?", answer: "Option Pool (or ESOP)" },
  { question: "What is the full name of the organization that publishes the widely used GAAP accounting standards?", answer: "Financial Accounting Standards Board (FASB)" },
  { question: "Which major investment bank had to be acquired by JPMorgan Chase during the 2008 financial crisis?", answer: "Bear Stearns" },
  { question: "What is the legal term for using someone else's copyrighted work without permission in a way that generates profit?", answer: "Infringement" },
  { question: "What is the name of the document created by a bank or syndicate that outlines the terms of a loan or bond issue?", answer: "Indenture" },
  { question: "What is the process of dividing a total market into distinct subsets of customers who have similar needs?", answer: "Market Segmentation" },
  { question: "What European pharmaceutical company developed the drugs Aspirin and Heroin (commercially)?", answer: "Bayer" },
  { question: "Who coined the phrase 'The customer is always right'?", answer: "Harry Gordon Selfridge (or Marshall Field)" },
  { question: "What is the common term for the non-compete clause that prevents a founder from starting a similar business after leaving?", answer: "Restrictive Covenant" },
  { question: "The 'Hedgehog Concept,' made famous by Jim Collins, advises companies to focus on three intersecting circles. Name two.", answer: "What you can be best in the world at; What drives your economic engine; What you are deeply passionate about" },
  { question: "What is the common name for the financial analysis technique that calculates the required sales volume to cover all costs?", answer: "Break-Even Analysis" },
  { question: "What is the name of the legal mechanism that allows a founder's equity to be earned over time?", answer: "Vesting" },
  { question: "What does the abbreviation 'KPI' stand for in business analytics?", answer: "Key Performance Indicator" },
  { question: "What company originally developed the Java programming language?", answer: "Sun Microsystems" },
  { question: "Which company is the world's largest defense contractor?", answer: "Lockheed Martin" },
  { question: "What is the most widely used enterprise resource planning (ERP) software company?", answer: "SAP" },
  { question: "What is the term for a type of stock that has priority over common stock regarding dividends and asset distribution?", answer: "Preferred Stock" },
  { question: "What is the term for the financial reporting manipulation that involves accelerating revenue recognition or deferring expenses?", answer: "Earnings management (or Cooking the books)" },
  { question: "What famous venture capitalist is known for his 'Zero to One' book and co-founding PayPal?", answer: "Peter Thiel" },
  { question: "What is the term for the strategy where a company offers a basic product for free and charges for premium features?", answer: "Freemium" },
  { question: "The 'Triple Bottom Line' is an accounting framework focusing on profit, people, and what else?", answer: "Planet" },
  { question: "What is the common term for the tax provision that allows a startup to carry forward losses to offset future taxable income?", answer: "Net Operating Loss (NOL) Carryforward" },
  { question: "What is the primary legal difference between a Merger and a Consolidation?", answer: "A Merger combines two firms into one existing one; a Consolidation forms a brand new entity" },
  { question: "What is the name of the financial model used to estimate the value of an asset based on the present value of future dividends?", answer: "Dividend Discount Model (DDM)" },
  { question: "What is the key difference between restricted stock and restricted stock units (RSUs)?", answer: "Restricted stock is a grant of actual stock; RSUs are a promise to grant stock at a future date (vesting)" },
  { question: "What famous automotive pioneer once served as the CEO of Chrysler and saved it from bankruptcy in the 1980s?", answer: "Lee Iacocca" },
  { question: "What is the common term for a public offering of securities following the IPO?", answer: "Secondary offering (or Follow-on offering)" },
  { question: "What famous economist wrote 'The Wealth of Nations'?", answer: "Adam Smith" },
  { question: "What color do you get when you mix red and yellow?", answer: "Orange" },
{ question: "How many legs does a spider have?", answer: "8" },
{ question: "What animal is known as the King of the Jungle?", answer: "Lion" },
{ question: "What fruit is yellow and curved?", answer: "Banana" },
{ question: "How many days are in a week?", answer: "7" },
{ question: "What do you call a baby dog?", answer: "Puppy" },
{ question: "What color is a stop sign?", answer: "Red" },
{ question: "In which hand does the Statue of Liberty hold her torch?", answer: "Right" },
{ question: "What is the name of the fairy in Peter Pan?", answer: "Tinker Bell" },
{ question: "How many sides does a triangle have?", answer: "3" },
{ question: "What do bees make that we can eat?", answer: "Honey" },
{ question: "What color are Smurfs?", answer: "Blue" },
{ question: "What animal says 'meow'?", answer: "Cat" },
{ question: "How many players are on a soccer team on the field?", answer: "11" },
{ question: "What is the name of Mickey Mouse's dog?", answer: "Pluto" },
{ question: "What is the biggest ocean?", answer: "Pacific Ocean" },
{ question: "What gas do we breathe in to live?", answer: "Oxygen" },
{ question: "How many letters are in the English alphabet?", answer: "26" },
{ question: "What toy cowboy is the main character in Toy Story?", answer: "Woody" },
{ question: "What drink comes from cows?", answer: "Milk" },
{ question: "What color is the circle on the Japanese flag?", answer: "Red" },
{ question: "How many wheels does a bicycle have?", answer: "2" },
{ question: "What is frozen water called?", answer: "Ice" },
{ question: "Which Disney movie has a princess named Elsa?", answer: "Frozen" },
{ question: "What animal is the tallest in the world?", answer: "Giraffe" },
{ question: "How many continents are there?", answer: "7" },
{ question: "What is the hottest planet in our solar system?", answer: "Venus" },
{ question: "What do you call the person who flies an airplane?", answer: "Pilot" },
{ question: "What color is grass when it's healthy?", answer: "Green" },
{ question: "What is the main ingredient in chocolate?", answer: "Cocoa" },
{ question: "How many zeros are in the number one thousand?", answer: "3" },
{ question: "What animal is known for its black and white stripes?", answer: "Zebra" },
{ question: "What fruit is used to make wine?", answer: "Grapes" },
{ question: "What is the name of the big green ogre in the Shrek movies?", answer: "Shrek" },
{ question: "How many fingers do most people have on one hand?", answer: "5" },
{ question: "What color is the sky on a clear day?", answer: "Blue" },
{ question: "What do you use to write on a blackboard?", answer: "Chalk" },
{ question: "What animal is the fastest on land?", answer: "Cheetah" },
{ question: "What is the house made of gingerbread associated with?", answer: "Christmas" },
{ question: "What is the name of the snowman in Frozen?", answer: "Olaf" },

// Medium difficulty (120 questions)
{ question: "What is the capital of France?", answer: "Paris" },
{ question: "Who painted the Mona Lisa?", answer: "Leonardo da Vinci" },
{ question: "What is the largest planet in our solar system?", answer: "Jupiter" },
{ question: "In which year did the Titanic sink?", answer: "1912" },
{ question: "What is the currency of Japan?", answer: "Yen" },
{ question: "Who was the first person to walk on the moon?", answer: "Neil Armstrong" },
{ question: "What is the longest river in the world?", answer: "Nile" },
{ question: "Which country is famous for inventing pizza?", answer: "Italy" },
{ question: "What is the chemical symbol for gold?", answer: "Au" },
{ question: "How many bones are in an adult human body?", answer: "206" },
{ question: "Who wrote 'Romeo and Juliet'?", answer: "William Shakespeare" },
{ question: "What is the capital of Brazil?", answer: "Brasília" },
{ question: "Which planet is known as the Red Planet?", answer: "Mars" },
{ question: "What is the hardest natural substance on Earth?", answer: "Diamond" },
{ question: "Who discovered penicillin?", answer: "Alexander Fleming" },
{ question: "What is the tallest mountain in the world?", answer: "Mount Everest" },
{ question: "In which year did World War II end?", answer: "1945" },
{ question: "What is the capital of Egypt?", answer: "Cairo" },
{ question: "Which element has atomic number 1?", answer: "Hydrogen" },
{ question: "What is the largest mammal in the world?", answer: "Blue whale" },
{ question: "Who painted 'The Starry Night'?", answer: "Vincent van Gogh" },
{ question: "What is the capital of Australia?", answer: "Canberra" },
{ question: "How many Harry Potter books are there?", answer: "7" },
{ question: "Which country is known as the Land of the Rising Sun?", answer: "Japan" },
{ question: "What is the deepest point in the ocean?", answer: "Mariana Trench" },
{ question: "Who developed the theory of relativity?", answer: "Albert Einstein" },
{ question: "Which country has the most population (2025)?", answer: "India" },
{ question: "What is the capital of Canada?", answer: "Ottawa" },
{ question: "Which planet has the most moons?", answer: "Saturn" },
{ question: "Who wrote 'Pride and Prejudice'?", answer: "Jane Austen" },
{ question: "What is the largest country by land area?", answer: "Russia" },
{ question: "Who was the first President of the United States?", answer: "George Washington" },
{ question: "What is the capital of Thailand?", answer: "Bangkok" },
{ question: "Which element is diamond made of?", answer: "Carbon" },
{ question: "Who invented the telephone?", answer: "Alexander Graham Bell" },
{ question: "What is the capital of Argentina?", answer: "Buenos Aires" },
{ question: "Which country hosted the 2016 Summer Olympics?", answer: "Brazil" },
{ question: "What is the largest desert in the world?", answer: "Antarctica" },
{ question: "Who wrote 'To Kill a Mockingbird'?", answer: "Harper Lee" },
{ question: "What is the capital of Portugal?", answer: "Lisbon" },
{ question: "Which country is home to the Great Barrier Reef?", answer: "Australia" },
{ question: "Who was the first woman to fly solo across the Atlantic?", answer: "Amelia Earhart" },
{ question: "What is the capital of South Africa (administrative)?", answer: "Pretoria" },
{ question: "Which bird lays the largest eggs?", answer: "Ostrich" },
{ question: "Who directed 'Jurassic Park'?", answer: "Steven Spielberg" },
{ question: "What is the capital of Iceland?", answer: "Reykjavík" },
{ question: "Which metal is liquid at room temperature?", answer: "Mercury" },
{ question: "What is the most spoken language in the world?", answer: "Mandarin Chinese" },
{ question: "Who was the Greek god of the sea?", answer: "Poseidon" },
{ question: "What is the capital of New Zealand?", answer: "Wellington" },
{ question: "What is the largest island in the world?", answer: "Greenland" },
{ question: "Who discovered America in 1492?", answer: "Christopher Columbus" },
{ question: "What is the capital of Norway?", answer: "Oslo" },
{ question: "Which country consumes the most chocolate per capita?", answer: "Switzerland" },
{ question: "What is the main ingredient in guacamole?", answer: "Avocado" },
{ question: "Who composed the 'Four Seasons'?", answer: "Antonio Vivaldi" },
{ question: "How many stars are on the current U.S. flag?", answer: "50" },
{ question: "What is the only number spelled with letters in alphabetical order?", answer: "Forty" },
{ question: "Who is the king of the gods in Greek mythology?", answer: "Zeus" },
{ question: "In what year was the first iPhone released?", answer: "2007" },
{ question: "Which country has won the most FIFA World Cups?", answer: "Brazil" },
{ question: "What is the holy book of Islam?", answer: "Qur’an" },
{ question: "Who wrote 'The Cat in the Hat'?", answer: "Dr. Seuss" },
{ question: "How many stripes are on the American flag?", answer: "13" },
{ question: "Which band’s logo is a tongue sticking out?", answer: "The Rolling Stones" },
{ question: "What does the Nike swoosh represent?", answer: "The wing of the Greek goddess Nike" },
{ question: "Which movie won the first ever Best Picture Oscar?", answer: "Wings" },
{ question: "Who was the youngest elected U.S. president?", answer: "John F. Kennedy" },
{ question: "How many members are in the U.S. Senate?", answer: "100" },
{ question: "Which country invented the sport of curling?", answer: "Scotland" },
{ question: "What is the highest-grossing animated movie of all time (2025)?", answer: "The Lion King (2019 remake)" },
{ question: "Who played Jack in Titanic?", answer: "Leonardo DiCaprio" },
{ question: "What is the chemical symbol for water?", answer: "H₂O" },
{ question: "Which spice is the most expensive by weight?", answer: "Saffron" },
{ question: "Who is credited with inventing the World Wide Web?", answer: "Tim Berners-Lee" },
{ question: "What is the largest moon of Saturn?", answer: "Titan" },
{ question: "How many Oscars did Titanic (1997) win?", answer: "11" },
{ question: "Which boxer was known as 'The Greatest'?", answer: "Muhammad Ali" },
{ question: "What is the only edible food that never goes bad?", answer: "Honey" },
{ question: "Which composer became deaf but kept composing?", answer: "Ludwig van Beethoven" },
{ question: "How many dimples are on a standard golf ball?", answer: "336" },
{ question: "Which country has the most Olympic gold medals ever?", answer: "United States" },
{ question: "What is the longest bone in the human body?", answer: "Femur" },
{ question: "Which movie has the line 'Here's looking at you, kid'?", answer: "Casablanca" },
{ question: "Who wrote '1984'?", answer: "George Orwell" },
{ question: "What is the capital of Kenya?", answer: "Nairobi" },
{ question: "Which planet has a day longer than its year?", answer: "Venus" },
{ question: "What is the only letter not used in any U.S. state name?", answer: "Q" },
{ question: "Which country’s flag is the only non-rectangular national flag?", answer: "Nepal" },
{ question: "What is the dot over the lowercase 'i' or 'j' called?", answer: "Tittle" },
{ question: "Which African country was never colonized by Europeans?", answer: "Ethiopia" },
{ question: "What is the shortest war in history (38 minutes)?", answer: "Anglo-Zanzibar War" },
{ question: "What gas, discovered on the sun before Earth, is the second-most abundant element in the universe?", answer: "Helium" },
{ question: "Which word has the most definitions in the Oxford English Dictionary?", answer: "Set" },
{ question: "What is the longest English word using only one vowel?", answer: "Strengths" },
{ question: "What is the fear of long words called?", answer: "Hippopotomonstrosesquippedaliophobia" },
{ question: "What was Google originally called?", answer: "BackRub" },
{ question: "Which mammal is born with horns?", answer: "Giraffe" },
{ question: "Who was the youngest person to win a Nobel Prize?", answer: "Malala Yousafzai" },
{ question: "What is the only English word that ends in '-mt'?", answer: "Dreamt" },
{ question: "Which language has the most words according to dictionaries?", answer: "Korean" },
{ question: "In what year was the first successful human heart transplant?", answer: "1967" },
{ question: "Which probe was the first to land on Mars?", answer: "Viking 1" },
{ question: "What is the technical name for a hashtag symbol?", answer: "Octothorpe" },
{ question: "Which king of England had six wives?", answer: "Henry VIII" },
{ question: "What is the only letter that doesn’t appear on the periodic table?", answer: "J" }
];